# Form implementation generated from reading ui file '../spectroscope/spectroscope_settings_help.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SpectroScopeSettingsHelp(object):
    def setupUi(self, SpectroScopeSettingsHelp):
        SpectroScopeSettingsHelp.setObjectName("SpectroScopeSettingsHelp")
        SpectroScopeSettingsHelp.resize(1200, 700)
        self.verticalLayout = QtWidgets.QVBoxLayout(SpectroScopeSettingsHelp)
        self.verticalLayout.setObjectName("verticalLayout")
        self.helpTextEdit = QtWidgets.QPlainTextEdit(parent=SpectroScopeSettingsHelp)
        self.helpTextEdit.setUndoRedoEnabled(False)
        self.helpTextEdit.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByKeyboard|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.helpTextEdit.setObjectName("helpTextEdit")
        self.verticalLayout.addWidget(self.helpTextEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=SpectroScopeSettingsHelp)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SpectroScopeSettingsHelp)
        self.buttonBox.accepted.connect(SpectroScopeSettingsHelp.accept) # type: ignore
        self.buttonBox.rejected.connect(SpectroScopeSettingsHelp.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SpectroScopeSettingsHelp)
        SpectroScopeSettingsHelp.setTabOrder(self.helpTextEdit, self.buttonBox)

    def retranslateUi(self, SpectroScopeSettingsHelp):
        _translate = QtCore.QCoreApplication.translate
        SpectroScopeSettingsHelp.setWindowTitle(_translate("SpectroScopeSettingsHelp", "Help - SpectroScope"))
