# Form implementation generated from reading ui file 'spectroscope_persistence.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SpectroScopePersistence(object):
    def setupUi(self, SpectroScopePersistence):
        SpectroScopePersistence.setObjectName("SpectroScopePersistence")
        SpectroScopePersistence.resize(250, 130)
        self.verticalLayout = QtWidgets.QVBoxLayout(SpectroScopePersistence)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(parent=SpectroScopePersistence)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.decayFunctionComboBox = QtWidgets.QComboBox(parent=SpectroScopePersistence)
        self.decayFunctionComboBox.setObjectName("decayFunctionComboBox")
        self.decayFunctionComboBox.addItem("")
        self.decayFunctionComboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.decayFunctionComboBox)
        self.label = QtWidgets.QLabel(parent=SpectroScopePersistence)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.persistenceLengthSpinBox = QtWidgets.QSpinBox(parent=SpectroScopePersistence)
        self.persistenceLengthSpinBox.setProperty("value", 5)
        self.persistenceLengthSpinBox.setObjectName("persistenceLengthSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.persistenceLengthSpinBox)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=SpectroScopePersistence)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label_2.setBuddy(self.decayFunctionComboBox)
        self.label.setBuddy(self.persistenceLengthSpinBox)

        self.retranslateUi(SpectroScopePersistence)
        self.decayFunctionComboBox.setCurrentIndex(1)
        self.buttonBox.accepted.connect(SpectroScopePersistence.accept) # type: ignore
        self.buttonBox.rejected.connect(SpectroScopePersistence.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SpectroScopePersistence)
        SpectroScopePersistence.setTabOrder(self.decayFunctionComboBox, self.persistenceLengthSpinBox)
        SpectroScopePersistence.setTabOrder(self.persistenceLengthSpinBox, self.buttonBox)

    def retranslateUi(self, SpectroScopePersistence):
        _translate = QtCore.QCoreApplication.translate
        SpectroScopePersistence.setWindowTitle(_translate("SpectroScopePersistence", "Persistence - SpectroScope"))
        self.label_2.setText(_translate("SpectroScopePersistence", "Decay function:"))
        self.decayFunctionComboBox.setItemText(0, _translate("SpectroScopePersistence", "linear"))
        self.decayFunctionComboBox.setItemText(1, _translate("SpectroScopePersistence", "exponential"))
        self.label.setText(_translate("SpectroScopePersistence", "Persistence length:"))
